// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FixedAudioModel.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "FixedAudioModel.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace FixedAudioModel {

namespace {

const ::google::protobuf::Descriptor* TaskHeader_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TaskHeader_reflection_ = NULL;
const ::google::protobuf::Descriptor* ResultHeader_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ResultHeader_reflection_ = NULL;
const ::google::protobuf::Descriptor* ModelInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ModelInfo_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ModelInfo_StatusCode_descriptor_ = NULL;
const ::google::protobuf::Descriptor* LoadResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoadResult_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* LoadResult_StatusCode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_FixedAudioModel_2eproto() {
  protobuf_AddDesc_FixedAudioModel_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "FixedAudioModel.proto");
  GOOGLE_CHECK(file != NULL);
  TaskHeader_descriptor_ = file->message_type(0);
  static const int TaskHeader_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TaskHeader, tasklength_),
  };
  TaskHeader_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TaskHeader_descriptor_,
      TaskHeader::default_instance_,
      TaskHeader_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TaskHeader, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TaskHeader, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TaskHeader));
  ResultHeader_descriptor_ = file->message_type(1);
  static const int ResultHeader_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ResultHeader, resultlength_),
  };
  ResultHeader_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ResultHeader_descriptor_,
      ResultHeader::default_instance_,
      ResultHeader_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ResultHeader, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ResultHeader, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ResultHeader));
  ModelInfo_descriptor_ = file->message_type(2);
  static const int ModelInfo_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelInfo, taskid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelInfo, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelInfo, modelurl_),
  };
  ModelInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ModelInfo_descriptor_,
      ModelInfo::default_instance_,
      ModelInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ModelInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ModelInfo));
  ModelInfo_StatusCode_descriptor_ = ModelInfo_descriptor_->enum_type(0);
  LoadResult_descriptor_ = file->message_type(3);
  static const int LoadResult_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadResult, taskid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadResult, status_),
  };
  LoadResult_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LoadResult_descriptor_,
      LoadResult::default_instance_,
      LoadResult_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadResult, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadResult, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LoadResult));
  LoadResult_StatusCode_descriptor_ = LoadResult_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_FixedAudioModel_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TaskHeader_descriptor_, &TaskHeader::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ResultHeader_descriptor_, &ResultHeader::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ModelInfo_descriptor_, &ModelInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LoadResult_descriptor_, &LoadResult::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_FixedAudioModel_2eproto() {
  delete TaskHeader::default_instance_;
  delete TaskHeader_reflection_;
  delete ResultHeader::default_instance_;
  delete ResultHeader_reflection_;
  delete ModelInfo::default_instance_;
  delete ModelInfo_reflection_;
  delete LoadResult::default_instance_;
  delete LoadResult_reflection_;
}

void protobuf_AddDesc_FixedAudioModel_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025FixedAudioModel.proto\022\017FixedAudioModel"
    "\" \n\nTaskHeader\022\022\n\ntaskLength\030\001 \002(\007\"$\n\014Re"
    "sultHeader\022\024\n\014resultLength\030\002 \002(\007\"\213\001\n\tMod"
    "elInfo\022\016\n\006taskid\030\001 \002(\t\0225\n\006status\030\002 \002(\0162%"
    ".FixedAudioModel.ModelInfo.StatusCode\022\020\n"
    "\010modelUrl\030\003 \002(\014\"%\n\nStatusCode\022\n\n\006FALURE\020"
    "\000\022\013\n\007SUCCESS\020\001\"{\n\nLoadResult\022\016\n\006taskid\030\001"
    " \002(\t\0226\n\006status\030\002 \002(\0162&.FixedAudioModel.L"
    "oadResult.StatusCode\"%\n\nStatusCode\022\n\n\006FA"
    "LURE\020\000\022\013\n\007SUCCESS\020\001B+\n\030com.thinkit.proto"
    "buf.msgB\017FixedAudioModel", 424);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "FixedAudioModel.proto", &protobuf_RegisterTypes);
  TaskHeader::default_instance_ = new TaskHeader();
  ResultHeader::default_instance_ = new ResultHeader();
  ModelInfo::default_instance_ = new ModelInfo();
  LoadResult::default_instance_ = new LoadResult();
  TaskHeader::default_instance_->InitAsDefaultInstance();
  ResultHeader::default_instance_->InitAsDefaultInstance();
  ModelInfo::default_instance_->InitAsDefaultInstance();
  LoadResult::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FixedAudioModel_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_FixedAudioModel_2eproto {
  StaticDescriptorInitializer_FixedAudioModel_2eproto() {
    protobuf_AddDesc_FixedAudioModel_2eproto();
  }
} static_descriptor_initializer_FixedAudioModel_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int TaskHeader::kTaskLengthFieldNumber;
#endif  // !_MSC_VER

TaskHeader::TaskHeader()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:FixedAudioModel.TaskHeader)
}

void TaskHeader::InitAsDefaultInstance() {
}

TaskHeader::TaskHeader(const TaskHeader& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:FixedAudioModel.TaskHeader)
}

void TaskHeader::SharedCtor() {
  _cached_size_ = 0;
  tasklength_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TaskHeader::~TaskHeader() {
  // @@protoc_insertion_point(destructor:FixedAudioModel.TaskHeader)
  SharedDtor();
}

void TaskHeader::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TaskHeader::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TaskHeader::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TaskHeader_descriptor_;
}

const TaskHeader& TaskHeader::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FixedAudioModel_2eproto();
  return *default_instance_;
}

TaskHeader* TaskHeader::default_instance_ = NULL;

TaskHeader* TaskHeader::New() const {
  return new TaskHeader;
}

void TaskHeader::Clear() {
  tasklength_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TaskHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FixedAudioModel.TaskHeader)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required fixed32 taskLength = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &tasklength_)));
          set_has_tasklength();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FixedAudioModel.TaskHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FixedAudioModel.TaskHeader)
  return false;
#undef DO_
}

void TaskHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FixedAudioModel.TaskHeader)
  // required fixed32 taskLength = 1;
  if (has_tasklength()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(1, this->tasklength(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FixedAudioModel.TaskHeader)
}

::google::protobuf::uint8* TaskHeader::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:FixedAudioModel.TaskHeader)
  // required fixed32 taskLength = 1;
  if (has_tasklength()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(1, this->tasklength(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FixedAudioModel.TaskHeader)
  return target;
}

int TaskHeader::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required fixed32 taskLength = 1;
    if (has_tasklength()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TaskHeader::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TaskHeader* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TaskHeader*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TaskHeader::MergeFrom(const TaskHeader& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_tasklength()) {
      set_tasklength(from.tasklength());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TaskHeader::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TaskHeader::CopyFrom(const TaskHeader& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TaskHeader::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void TaskHeader::Swap(TaskHeader* other) {
  if (other != this) {
    std::swap(tasklength_, other->tasklength_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TaskHeader::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TaskHeader_descriptor_;
  metadata.reflection = TaskHeader_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ResultHeader::kResultLengthFieldNumber;
#endif  // !_MSC_VER

ResultHeader::ResultHeader()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:FixedAudioModel.ResultHeader)
}

void ResultHeader::InitAsDefaultInstance() {
}

ResultHeader::ResultHeader(const ResultHeader& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:FixedAudioModel.ResultHeader)
}

void ResultHeader::SharedCtor() {
  _cached_size_ = 0;
  resultlength_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ResultHeader::~ResultHeader() {
  // @@protoc_insertion_point(destructor:FixedAudioModel.ResultHeader)
  SharedDtor();
}

void ResultHeader::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ResultHeader::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ResultHeader::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ResultHeader_descriptor_;
}

const ResultHeader& ResultHeader::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FixedAudioModel_2eproto();
  return *default_instance_;
}

ResultHeader* ResultHeader::default_instance_ = NULL;

ResultHeader* ResultHeader::New() const {
  return new ResultHeader;
}

void ResultHeader::Clear() {
  resultlength_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ResultHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FixedAudioModel.ResultHeader)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required fixed32 resultLength = 2;
      case 2: {
        if (tag == 21) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &resultlength_)));
          set_has_resultlength();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FixedAudioModel.ResultHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FixedAudioModel.ResultHeader)
  return false;
#undef DO_
}

void ResultHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FixedAudioModel.ResultHeader)
  // required fixed32 resultLength = 2;
  if (has_resultlength()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(2, this->resultlength(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FixedAudioModel.ResultHeader)
}

::google::protobuf::uint8* ResultHeader::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:FixedAudioModel.ResultHeader)
  // required fixed32 resultLength = 2;
  if (has_resultlength()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(2, this->resultlength(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FixedAudioModel.ResultHeader)
  return target;
}

int ResultHeader::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required fixed32 resultLength = 2;
    if (has_resultlength()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ResultHeader::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ResultHeader* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ResultHeader*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ResultHeader::MergeFrom(const ResultHeader& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_resultlength()) {
      set_resultlength(from.resultlength());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ResultHeader::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResultHeader::CopyFrom(const ResultHeader& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResultHeader::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void ResultHeader::Swap(ResultHeader* other) {
  if (other != this) {
    std::swap(resultlength_, other->resultlength_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ResultHeader::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ResultHeader_descriptor_;
  metadata.reflection = ResultHeader_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* ModelInfo_StatusCode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ModelInfo_StatusCode_descriptor_;
}
bool ModelInfo_StatusCode_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ModelInfo_StatusCode ModelInfo::FALURE;
const ModelInfo_StatusCode ModelInfo::SUCCESS;
const ModelInfo_StatusCode ModelInfo::StatusCode_MIN;
const ModelInfo_StatusCode ModelInfo::StatusCode_MAX;
const int ModelInfo::StatusCode_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int ModelInfo::kTaskidFieldNumber;
const int ModelInfo::kStatusFieldNumber;
const int ModelInfo::kModelUrlFieldNumber;
#endif  // !_MSC_VER

ModelInfo::ModelInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:FixedAudioModel.ModelInfo)
}

void ModelInfo::InitAsDefaultInstance() {
}

ModelInfo::ModelInfo(const ModelInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:FixedAudioModel.ModelInfo)
}

void ModelInfo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  taskid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_ = 0;
  modelurl_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ModelInfo::~ModelInfo() {
  // @@protoc_insertion_point(destructor:FixedAudioModel.ModelInfo)
  SharedDtor();
}

void ModelInfo::SharedDtor() {
  if (taskid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete taskid_;
  }
  if (modelurl_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete modelurl_;
  }
  if (this != default_instance_) {
  }
}

void ModelInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ModelInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ModelInfo_descriptor_;
}

const ModelInfo& ModelInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FixedAudioModel_2eproto();
  return *default_instance_;
}

ModelInfo* ModelInfo::default_instance_ = NULL;

ModelInfo* ModelInfo::New() const {
  return new ModelInfo;
}

void ModelInfo::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_taskid()) {
      if (taskid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        taskid_->clear();
      }
    }
    status_ = 0;
    if (has_modelurl()) {
      if (modelurl_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        modelurl_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ModelInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FixedAudioModel.ModelInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string taskid = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_taskid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->taskid().data(), this->taskid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "taskid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_status;
        break;
      }

      // required .FixedAudioModel.ModelInfo.StatusCode status = 2;
      case 2: {
        if (tag == 16) {
         parse_status:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::FixedAudioModel::ModelInfo_StatusCode_IsValid(value)) {
            set_status(static_cast< ::FixedAudioModel::ModelInfo_StatusCode >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_modelUrl;
        break;
      }

      // required bytes modelUrl = 3;
      case 3: {
        if (tag == 26) {
         parse_modelUrl:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_modelurl()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FixedAudioModel.ModelInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FixedAudioModel.ModelInfo)
  return false;
#undef DO_
}

void ModelInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FixedAudioModel.ModelInfo)
  // required string taskid = 1;
  if (has_taskid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->taskid().data(), this->taskid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "taskid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->taskid(), output);
  }

  // required .FixedAudioModel.ModelInfo.StatusCode status = 2;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->status(), output);
  }

  // required bytes modelUrl = 3;
  if (has_modelurl()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->modelurl(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FixedAudioModel.ModelInfo)
}

::google::protobuf::uint8* ModelInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:FixedAudioModel.ModelInfo)
  // required string taskid = 1;
  if (has_taskid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->taskid().data(), this->taskid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "taskid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->taskid(), target);
  }

  // required .FixedAudioModel.ModelInfo.StatusCode status = 2;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->status(), target);
  }

  // required bytes modelUrl = 3;
  if (has_modelurl()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->modelurl(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FixedAudioModel.ModelInfo)
  return target;
}

int ModelInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string taskid = 1;
    if (has_taskid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->taskid());
    }

    // required .FixedAudioModel.ModelInfo.StatusCode status = 2;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->status());
    }

    // required bytes modelUrl = 3;
    if (has_modelurl()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->modelurl());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ModelInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ModelInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ModelInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ModelInfo::MergeFrom(const ModelInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_taskid()) {
      set_taskid(from.taskid());
    }
    if (from.has_status()) {
      set_status(from.status());
    }
    if (from.has_modelurl()) {
      set_modelurl(from.modelurl());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ModelInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ModelInfo::CopyFrom(const ModelInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ModelInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void ModelInfo::Swap(ModelInfo* other) {
  if (other != this) {
    std::swap(taskid_, other->taskid_);
    std::swap(status_, other->status_);
    std::swap(modelurl_, other->modelurl_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ModelInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ModelInfo_descriptor_;
  metadata.reflection = ModelInfo_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* LoadResult_StatusCode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoadResult_StatusCode_descriptor_;
}
bool LoadResult_StatusCode_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const LoadResult_StatusCode LoadResult::FALURE;
const LoadResult_StatusCode LoadResult::SUCCESS;
const LoadResult_StatusCode LoadResult::StatusCode_MIN;
const LoadResult_StatusCode LoadResult::StatusCode_MAX;
const int LoadResult::StatusCode_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int LoadResult::kTaskidFieldNumber;
const int LoadResult::kStatusFieldNumber;
#endif  // !_MSC_VER

LoadResult::LoadResult()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:FixedAudioModel.LoadResult)
}

void LoadResult::InitAsDefaultInstance() {
}

LoadResult::LoadResult(const LoadResult& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:FixedAudioModel.LoadResult)
}

void LoadResult::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  taskid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LoadResult::~LoadResult() {
  // @@protoc_insertion_point(destructor:FixedAudioModel.LoadResult)
  SharedDtor();
}

void LoadResult::SharedDtor() {
  if (taskid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete taskid_;
  }
  if (this != default_instance_) {
  }
}

void LoadResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoadResult::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoadResult_descriptor_;
}

const LoadResult& LoadResult::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FixedAudioModel_2eproto();
  return *default_instance_;
}

LoadResult* LoadResult::default_instance_ = NULL;

LoadResult* LoadResult::New() const {
  return new LoadResult;
}

void LoadResult::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_taskid()) {
      if (taskid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        taskid_->clear();
      }
    }
    status_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool LoadResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FixedAudioModel.LoadResult)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string taskid = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_taskid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->taskid().data(), this->taskid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "taskid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_status;
        break;
      }

      // required .FixedAudioModel.LoadResult.StatusCode status = 2;
      case 2: {
        if (tag == 16) {
         parse_status:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::FixedAudioModel::LoadResult_StatusCode_IsValid(value)) {
            set_status(static_cast< ::FixedAudioModel::LoadResult_StatusCode >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FixedAudioModel.LoadResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FixedAudioModel.LoadResult)
  return false;
#undef DO_
}

void LoadResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FixedAudioModel.LoadResult)
  // required string taskid = 1;
  if (has_taskid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->taskid().data(), this->taskid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "taskid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->taskid(), output);
  }

  // required .FixedAudioModel.LoadResult.StatusCode status = 2;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->status(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FixedAudioModel.LoadResult)
}

::google::protobuf::uint8* LoadResult::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:FixedAudioModel.LoadResult)
  // required string taskid = 1;
  if (has_taskid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->taskid().data(), this->taskid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "taskid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->taskid(), target);
  }

  // required .FixedAudioModel.LoadResult.StatusCode status = 2;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->status(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FixedAudioModel.LoadResult)
  return target;
}

int LoadResult::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string taskid = 1;
    if (has_taskid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->taskid());
    }

    // required .FixedAudioModel.LoadResult.StatusCode status = 2;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->status());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoadResult::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const LoadResult* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const LoadResult*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void LoadResult::MergeFrom(const LoadResult& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_taskid()) {
      set_taskid(from.taskid());
    }
    if (from.has_status()) {
      set_status(from.status());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void LoadResult::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoadResult::CopyFrom(const LoadResult& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoadResult::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void LoadResult::Swap(LoadResult* other) {
  if (other != this) {
    std::swap(taskid_, other->taskid_);
    std::swap(status_, other->status_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata LoadResult::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoadResult_descriptor_;
  metadata.reflection = LoadResult_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace FixedAudioModel

// @@protoc_insertion_point(global_scope)
