
export
.PHONY: build buildall

build:
	@echo ============================================
	@echo ">>>>>>>>>>>>>>>>>>>start building libinterface.so<<<<<<<<<<<<<<<<<<<<<"
	@echo ============================================
	${MAKE} -f MakefileNew -f MakefileCpp

buildall: build build242
